INSERT INTO USER_TYPE (USERTYPE_ID, USER_TYPE)
VALUES (1, 'Student'),
        (2, 'Teacher');

INSERT INTO USER (USER_ID, BORROWED_BOOKS, EMAIL, FIRST_NAME, LAST_NAME, PHONE, USER_CODE, USERTYPE_ID, IS_ACTIVE)
VALUES (1, 3, 'cris.mundo@outlook.com', 'Cristian', 'Mundo', '(503) 7678-3896', 86917, 1, TRUE);

INSERT INTO USER (USER_ID, BORROWED_BOOKS, EMAIL, FIRST_NAME, LAST_NAME, PHONE, USER_CODE, USERTYPE_ID, IS_ACTIVE)
VALUES (2, 0, 'oswaldo.caceres@outlook.com', 'Oswaldo', 'Cáceres', '(502) 5378-2136', 2021, 2, TRUE);

INSERT INTO BOOK (BOOK_ID, AUTHOR, CATEGORY, IS_AVAILABLE, ISBN, TITLE)
VALUES (1, 'Agatha Christie', 'Mistery', false, 3399, 'Los diez negritos');
INSERT INTO BOOK (BOOK_ID, AUTHOR, CATEGORY, IS_AVAILABLE, ISBN, TITLE)
VALUES (2, 'Will Smith', 'Biography', false, 2577, 'Will');
INSERT INTO BOOK (BOOK_ID, AUTHOR, CATEGORY, IS_AVAILABLE, ISBN, TITLE)
VALUES (3, 'League of Legends', 'Discovery, Drama', false, 3040, 'Arcane');
INSERT INTO BOOK (BOOK_ID, AUTHOR, CATEGORY, IS_AVAILABLE, ISBN, TITLE)
VALUES (4, 'Stephen Hawking', 'Science', true, 1988, 'A brief history of time');

INSERT INTO BOOK_RECORD (RECORD_ID, DELAY_PENALIZATION, DUE_DATE, IS_RETURNED, RENEWAL_CONT, RETURN_ON, TOOK_ON,
                         TRANSACTION_NUMBER, BOOK_BOOK_ID, USER_USER_ID)
VALUES (1, null, '2021-11-29', false , 0, null, '2021-11-22', 1000, 1, 1);

INSERT INTO BOOK_RECORD (RECORD_ID, DELAY_PENALIZATION, DUE_DATE, IS_RETURNED, RENEWAL_CONT, RETURN_ON, TOOK_ON,
                         TRANSACTION_NUMBER, BOOK_BOOK_ID, USER_USER_ID)
VALUES (2, null, '2021-11-27', false, 1, null, '2021-11-20', 2000, 2, 1);

INSERT INTO BOOK_RECORD (RECORD_ID, DELAY_PENALIZATION, DUE_DATE, IS_RETURNED, RENEWAL_CONT, RETURN_ON, TOOK_ON,
                         TRANSACTION_NUMBER, BOOK_BOOK_ID, USER_USER_ID)
VALUES (3, null, '2021-11-22', false, 0, null, '2021-11-15', 3000, 3, 1);
